server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
## 配置数据源信息
#############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP。spring默认的，不用引入依赖
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql8 以后默认的
    # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 10 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1

############################################################
## mybatis 配置
#############################################################
mybatis:
  type-aliases-package: com.imooc.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:com.imooc.mapper/*.xml # mapper映射文件

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl